### ISSUE TITLE
Twitch IRC migration?

### ISSUE THREAD

**Issue by ddugovic** [vincentsimard/vsimbot#4]
Either I'm misunderstanding [something](https://discuss.dev.twitch.tv/t/psa-chat-servers-are-going-to-migrate-to-aws-ec2-servers/4877) or I cannot authenticate my bot to `irc.chat.twitch.tv`...

```
$ node index.js 
(node:30969) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Request to use token, but token was unavailable to the client.
[17:13:26] 11 Jan 17:13:26 - Sending irc NICK/USER
[17:13:26] *** connecting to irc.chat.twitch.tv... 
[17:13:27] 11 Jan 17:13:27 - SEND: PASS password
[17:13:29] 11 Jan 17:13:29 - SEND: NICK godelescherbot
[17:13:31] 11 Jan 17:13:31 - SEND: USER godelescherbot 8 * vsimbot
[17:13:40] 11 Jan 17:13:40 - Connection got "end" event
[17:13:40] 11 Jan 17:13:40 - Connection got "close" event
[17:13:40] 11 Jan 17:13:40 - Disconnected: reconnecting
[17:13:40] 11 Jan 17:13:40 - Waiting 2000ms before retrying
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at TLSSocket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by ddugovic** [comment]
At this point the larger issue is that `npm ci` fails unconditionally:
https://github.com/ddugovic/vsimbot/actions
